name: wanxin_info_spider
allowed_domains: ["wanxin20.github.io"]
start_urls: ["https://wanxin20.github.io/ceshi/"]
max_pages: 1  # 单页面网站
list_rules:
  person_items: '//div[@class="person-info"]'
detail_rules:
  name: './/div[@class="info-item"][1]/span[@class="info-value"]/text()'
  age: './/div[@class="info-item"][2]/span[@class="info-value"]/text()'
  position: './/div[@class="info-item"][3]/span[@class="info-value"]/text()'
  department: './/div[@class="info-item"][4]/span[@class="info-value"]/text()'
  save_path: "data/policy_data/wanxin_info"